domains:
  - title: "General"
    modules:
      - title: "St. Jude Cloud"
        subtitle: "Guides that span across St. Jude Cloud."
        path: /docs/
        icon: stjudecloud-blue-circle-logo.svg
        chapters:
          - title:
            pages:
              - title: "Overview"
                path: /docs/
              - title: "About our Ecosystem"
                path: /docs/ecosystem/
              - title: Citing St. Jude Cloud
                path: /docs/citing-stjude-cloud/
              - title: Frequently Asked Questions
                path: /docs/faq/
  - title: "Apps"
    modules:
      - title: "Genomics Platform"
        subtitle: "Genomics data and bioinformatics workflows."
        path: /docs/genomics-platform/
        icon: stjudecloud-genomics-platform-logo.svg
        chapters:
          - title: "Getting Started"
            collapsable: true
            pages:
              - title: "Accounts and Billing"
                path: /docs/genomics-platform/accounts-and-billing/
              - title: "Making a Data Request"
                path: /docs/genomics-platform/requesting-data/making-a-data-request/
              - title: "Filling Out the DAA"
                path: /docs/genomics-platform/requesting-data/how-to-fill-out-daa/
              - title: "Frequently Asked Questions"
                path: /docs/genomics-platform/faq/
          - title: "About Our Data"
            collapsable: true
            pages:
              - title: "Data Sets and Data Access Units"
                path: /docs/genomics-platform/about-our-data/dau-and-datasets/
              - title: "File Formats and Sequencing Information"
                path: /docs/genomics-platform/about-our-data/file-formats-and-sequencing/
              - title: "Metadata and Clinical Information"
                path: /docs/genomics-platform/about-our-data/metadata-and-clinical/
          - title: "Managing Data"
            collapsable: true
            pages:
              - title: "Overview"
                path: /docs/genomics-platform/managing-data/working-with-our-data/
              - title: "Upload / Download Data (Local)"
                path: /docs/genomics-platform/managing-data/upload-local/
              - title: "Upload / Download Data (Cluster)"
                path: /docs/genomics-platform/managing-data/upload-cluster/
              - title: "Upload / Download Data (DNAnexus)"
                path: /docs/genomics-platform/managing-data/upload-dnanexus/
              - title: "Renewing Your DAA"
                path: /docs/genomics-platform/managing-data/how-to-fill-out-extension/
          - title: "Analyzing Data"
            collapsable: true
            pages:
              - title: "Command Line Interaction"
                path: /docs/genomics-platform/analyzing-data/command-line/
              - title: "Running Our Workflows"
                path: /docs/genomics-platform/analyzing-data/running-sj-workflows/
              - title: "Creating a Cloud App"
                path: /docs/genomics-platform/analyzing-data/creating-a-cloud-app/
              - title: "Interactive Nodes"
                path: /docs/genomics-platform/analyzing-data/interactive-node/
              - title: "Visualizing NGS Data"
                path: /docs/genomics-platform/analyzing-data/visualizing-ngs-data/
          - title: "Workflow Guides"
            collapsable: true
            pages:
              - title: "ChIP-Seq Peak Calling"
                path: /docs/genomics-platform/workflow-guides/chipseq/
              - title: "cis-X"
                path: /docs/genomics-platform/workflow-guides/cis-x/
              - title: "MethylationToActivity"
                path: /docs/genomics-platform/workflow-guides/methylation-to-activity/
              - title: "Mutational Signatures"
                path: /docs/genomics-platform/workflow-guides/mutational-signatures/
              - title: "Rapid RNA-Seq"
                path: /docs/genomics-platform/workflow-guides/rapid-rnaseq/
              - title: "RNA Seq Expression Classification"
                path: /docs/genomics-platform/workflow-guides/rnaseq-expression-classification/
              - title: "SEAseq"
                path: /docs/genomics-platform/workflow-guides/seaseq/
              - title: "SequencErr"
                path: /docs/genomics-platform/workflow-guides/sequencerr/
              - title: "WARDEN Differential Gene Expression"
                path: /docs/genomics-platform/workflow-guides/warden/
      - title: "PeCan"
        subtitle: "Explore the pediatric cancer knowledgebase."
        path: /docs/pecan/
        icon: stjudecloud-pecan-logo.svg
        chapters:
          - title: "Getting Started"
            pages:
              - title: "PeCan PIE"
                path: /docs/pecan/pecan-pie/
              - title: Frequently Asked Questions
                path: /docs/pecan/faq/
      - title: "Visualization Community"
        subtitle: "Create and share genomic visualizations."
        path: /docs/visualization-community/
        icon: stjudecloud-visualization-community-logo.svg
        chapters:
          - title: "Getting Started"
            pages:
              - title: "What is Visualizaton Community"
                path: /docs/visualization-community/
              - title: "What are ProteinPaint and GenomePaint"
                path: /docs/visualization-community/whatare
              - title: "Data Types"
                path: /docs/visualization-community/datatypes/
              - title: "FAQ"
                path: /docs/visualization-community/faq/
          - title: "ProteinPaint"
            collapsable: true
            pages:
              - title: "Introduction"
                path: /docs/visualization-community/proteinpaint/introduction/
              - title: "Getting Started"
                path: /docs/visualization-community/proteinpaint/user-guide/getting-started/
              - title: "Loading Datasets"
                path: /docs/visualization-community/proteinpaint/user-guide/loading-datasets/
              - title: "Viewing SNV/Indel Mutations"
                path: /docs/visualization-community/proteinpaint/user-guide/view-mutation-details/
              - title: "Viewing Gene Fusions"
                path: /docs/visualization-community/proteinpaint/user-guide/exploring-gene-fusions/
              - title: "Viewing Expression Data"
                path: /docs/visualization-community/proteinpaint/user-guide/exploring-gene-expression/
              - title: "Filtering Mutations"
                path: /docs/visualization-community/proteinpaint/user-guide/filtering-mutations/
              - title: "Exporting Figures and Data"
                path: /docs/visualization-community/proteinpaint/user-guide/exporting-figures-and-data/
              - title: "Using the Gene Table"
                path: /docs/visualization-community/proteinpaint/user-guide/using-the-gene-table/
              - title: "Using the Sample Table"
                path: /docs/visualization-community/proteinpaint/user-guide/using-the-sample-table/
              - title: "Using the Heatmap"
                path: /docs/visualization-community/proteinpaint/user-guide/using-the-heatmap/
              - title: "Using Disease Pie Charts"
                path: /docs/visualization-community/proteinpaint/user-guide/using-disease-pie-charts/
              - title: "Stratifying Mutations by Cancer Subtype"
                path: /docs/visualization-community/proteinpaint/user-guide/stratify-mutations-by-cancer-subtype/
              - title: "SNV and Indel"
                path: /docs/visualization-community/proteinpaint/file-formats/snv-and-indel/
              - title: "SV and fusion transcript"
                path: /docs/visualization-community/proteinpaint/file-formats/sv-and-fusion/
              - title: "Copy Number Variants"
                path: /docs/visualization-community/proteinpaint/file-formats/cnv
              - title: "Internal Tandem Duplications"
                path: /docs/visualization-community/proteinpaint/file-formats/itd/
              - title: "Intragenic deletion"
                path: /docs/visualization-community/proteinpaint/file-formats/intragenic-deletion/
              - title: "Truncation, N-loss, or C-loss"
                path: /docs/visualization-community/proteinpaint/file-formats/truncation/
              - title: "JSON-BED"
                path: /docs/visualization-community/proteinpaint/file-formats/json-bed/
              - title: "Splice Junction"
                path: /docs/visualization-community/proteinpaint/file-formats/splice-junction/
              - title: "Profile-Gene-Value"
                path: /docs/visualization-community/proteinpaint/file-formats/pgv/
              - title: "Bampile"
                path: /docs/visualization-community/proteinpaint/file-formats/bampile/
              - title: "Add Custom Protein Domains"
                path: /docs/visualization-community/proteinpaint/advanced-guides/add-custom-protein-domains/
              - title: "Using Custom Tracks"
                path: /docs/visualization-community/proteinpaint/advanced-guides/using-custom-tracks/
              - title: "Visualize Your Mutation Data"
                path: /docs/visualization-community/proteinpaint/advanced-guides/visualize-custom-mutations/
              - title: "Loading SNV/Indel Mutations from a File"
                path: /docs/visualization-community/proteinpaint/advanced-guides/loading-snv-indel-data-from-a-file/
              - title: "Uploaded Mutation Data User Interface"
                path: /docs/visualization-community/proteinpaint/advanced-guides/uploaded-mutation-data-user-interface/
              - title: "Loading a TCGA MAF File"
                path: /docs/visualization-community/proteinpaint/advanced-guides/loading-tcga-maf-file/
              - title: "Using a VCF File"
                path: /docs/visualization-community/proteinpaint/advanced-guides/using-a-vcf-file/
              - title: "Embedding ProteinPaint"
                path: /docs/visualization-community/proteinpaint/developers-guide/embedding-proteinpaint/
              - title: "URL Parameters"
                path: /docs/visualization-community/proteinpaint/developers-guide/url-parameters/
              - title: "Organizing Data into a Study View"
                path: /docs/visualization-community/proteinpaint/developers-guide/organizing-data-into-a-study-view/
          - title: "GenomePaint"
            collapsable: true
            pages:
              - title: "GenomePaint"
                path: /docs/visualization-community/genomepaint/
              - title: "GenomePaint User Guide"
                path: /docs/visualization-community/genomepaint/user-guide/      
          - title: "Visualize Your Data"
            collapsable: true
            pages:
              - title: "Video Tutorials"
                path: /docs/visualization-community/tutorials/tutorial_videos/
              - title: "Embedding"
                path: /docs/visualization-community/tutorials/embed/
              - title: "VCF"
                path: /docs/visualization-community/tutorials/vcf/
              - title: "BAM"
                path: /docs/visualization-community/tutorials/bam/
              - title: "BigWig"
                path: /docs/visualization-community/tutorials/bigwig/
              - title: "BigWig Stranded"
                path: /docs/visualization-community/tutorials/bigwigstranded/
              - title: "Heatmap"
                path: /docs/visualization-community/tutorials/heatmap/
              - title: "Single Cell"
                path: /docs/visualization-community/tutorials/singlecell/
              - title: "Allelic Imbalance"
                path: /docs/visualization-community/tutorials/ai-check/
              - title: "Arc"
                path: /docs/visualization-community/tutorials/arc/
              - title: "Expression Rank"
                path: /docs/visualization-community/tutorials/expression-rank/
              - title: "Hi-C"
                path: /docs/visualization-community/tutorials/hic/
              - title: "Lollipop"
                path: /docs/visualization-community/tutorials/lollipop/
              - title: "MA Volcano"
                path: /docs/visualization-community/tutorials/MA-Volcano/
              - title: "Splice Junctions Cohort"
                path: /docs/visualization-community/tutorials/splice-junctions-cohort/
          #- title: "Other"
           #  modules:
          #- title: "Studies"
           #  subtitle: "Discover projects who have donated their data."
           #     path: /docs/studies/
           #    icon: stjudecloud-blue-circle-logo.svg
        #chapters:
          #- title: "Studies"
           # pages:
             # - title: "Sickle Cell"
             #   path: /docs/studies/sickle-cell/
      # - title: "Portals"
      #   subtitle: "Browse project-specific sites."
      #   path: /docs/portals/
      #   icon: stjudecloud-blue-circle-logo.svg
      #   chapters:
      #     - title: "Portals"
      #       pages:
      #         - title: "Childhood Solid Tumor Network Portal"
      #           path: /docs/portals/cstn/
      #         - title: "Pediatric Brain Tumor Portal"
      #           path: /docs/portals/pbtp/
